name: reteti-searcher

# RETETI_UID="$(id -u)" RETETI_GID="$(id -g)" docker compose --file docker-compose-searcher.yml down
# RETETI_UID="$(id -u)" RETETI_GID="$(id -g)" docker compose --file docker-compose-searcher.yml build --no-cache
# RETETI_UID="$(id -u)" RETETI_GID="$(id -g)" docker compose --file docker-compose-searcher.yml up --remove-orphans

services:
  searcher:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${RETETI_UID}:${RETETI_GID}"
    networks:
      - savanna
    ports:
      - "7860:7860"
    env_file: ".env"
    volumes:
      - .:/app
    command: python /app/demo_searcher.py

networks:
  savanna:
    driver: bridge
