name: reteti-indexer

# RETETI_UID="$(id -u)" RETETI_GID="$(id -g)" docker compose --file docker-compose-indexer.yml down
# RETETI_UID="$(id -u)" RETETI_GID="$(id -g)" docker compose --file docker-compose-indexer.yml build --no-cache
# RETETI_UID="$(id -u)" RETETI_GID="$(id -g)" docker compose --file docker-compose-indexer.yml up --remove-orphans

services:
  # minio:
  #   image: minio/minio
  #   user: "${RETETI_UID}:${RETETI_GID}"
  #   networks:
  #     - savanna
  #   hostname: minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   env_file: ".env"
  #   environment:
  #     - MINIO_ROOT_USER=${LOCAL_ACCESS_KEY_ID}
  #     - MINIO_ROOT_PASSWORD=${LOCAL_SECRET_ACCESS_KEY}
  #   volumes:
  #     - ./data/minio:/data
  #   command: server /data --address ":9000" --console-address ":9001"

  index-maker:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${RETETI_UID}:${RETETI_GID}"
    networks:
      - savanna
    env_file: ".env"
    volumes:
      - .:/app
    # depends_on:
    #   minio:
    #     condition: service_started
    volumes:
      - .:/app
    command: python /app/demo_indexer.py

networks:
  savanna:
    driver: bridge
