name: reteti-indexer

# RETETI_UID="$(id -u)" RETETI_GID="$(id -g)" docker compose --file docker-compose-indexer.yml down
# RETETI_UID="$(id -u)" RETETI_GID="$(id -g)" docker compose --file docker-compose-indexer.yml build --no-cache
# RETETI_UID="$(id -u)" RETETI_GID="$(id -g)" docker compose --file docker-compose-indexer.yml up --remove-orphans

services:
  index-maker:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${RETETI_UID}:${RETETI_GID}"
    env_file: ".env"
    volumes:
      - .:/app
    command: python /app/demo_indexer.py
